from .xtts import XTTSv2
from .bark import Bark
from .vits import Vits
from .glowtts import GlowTTS
from .fairseq import Fairseq
from .tortoise import Tortoise
from .tacotron import Tacotron2
from .yourtts import YourTTS
from .ttsapi import TTSApi
